Fix unused parameter warning in detail/signal_template.hpp
Clang 20 with -Wall -Wextra -Werror and Boost 1.88 raises this
warning/error:
/data/mwrep/res/osp/Boost/25-0-0-0/include/boost/signals2/detail/signal_template.hpp:778:75: error: unused parameter 'other' [-Werror,-Wunused-parameter]
  778 |         const BOOST_SIGNALS2_SIGNAL_CLASS_NAME(BOOST_SIGNALS2_NUM_ARGS) & other) BOOST_NOEXCEPT
      |                                                                           ^
1 error generated.