slot_base.hpp: clang gives compiler errors due to bad expression
I am trying to update to boost-1.62 but am hitting compiler errors:

/usr/local/include/boost/signals2/slot_base.hpp:70:29: error: expected value in expression
    #if(!BOOST_NO_EXCEPTIONS)
                            ^